# The URL the site will be built for
base_url = "https://skel.cc"

# The site title and description; used in feeds by default.
title = "SkeletonsAreBad"
description = "cool and good"

# The default language; used in feeds.
default_language = "en"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to do syntax highlighting
highlight_code = true
highlight_theme = "visual-studio-dark"

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

[extra]
# Put all your custom variables here
