backend:
  name: git-gateway
  branch: master
media_folder: static/img/uploads
public_folder: /img/uploads
collections:
  - name: "projects"
    label: "Projects"
    label_singular: "Project"
    folder: "content/p"
    format: toml-frontmatter
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string", required: true }
      - {
          label: "Description",
          name: "description",
          widget: "string",
          required: true,
        }
      - {
          label: "Post Date",
          name: "date",
          widget: "datetime",
          required: true,
          dateFormat: "YYYY-MM-DD",
        }
      - { label: "Feature Image", name: "extra.image", widget: "image" }
      - {
          label: "GitHub Repository",
          name: "extra.repository",
          widget: "list",
          allow_add: false,
          default: ["user", "name"],
        }
      - { label: "Body", name: "body", widget: "markdown", required: true }
