backend:
  name: git-gateway
  branch: master
media_folder: static/img/uploads
public_folder: /img/uploads
collections:
  - label: "Data"
    name: "data"
    files:
      - label: "Links"
        name: "Links"
        file: "content/links.json"
        fields:
          - label: "Social"
            name: "social"
            widget: "list"
            fields:
              - {
                  label: "Title",
                  name: "title",
                  widget: "string",
                  required: true,
                }
              - {
                  label: "Icon",
                  name: "icon",
                  widget: "string",
                  required: true,
                  default: "fab fa-",
                }
              - {
                  label: "Username",
                  name: "username",
                  widget: "string",
                  required: true,
                }
              - {
                  label: "URL",
                  name: "url",
                  widget: "string",
                  required: true,
                  default: "https://",
                }
  - label: "Projects"
    label_singular: "Project"
    name: "projects"
    folder: "content/p"
    format: toml-frontmatter
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string", required: true }
      - {
          label: "Description",
          name: "description",
          widget: "string",
          required: true,
        }
      - {
          label: "Post Date",
          name: "date",
          widget: "datetime",
          required: true,
          dateFormat: "YYYY-MM-DD",
        }
      - { label: "Body", name: "body", widget: "markdown", required: true }
